version: "3.4"
services:
  neko:
    image: "ghcr.io/m1k1o/neko/arm-ungoogled-chromium:latest"
    restart: "unless-stopped"
    shm_size: "16gb"
    ports:
      - "8080:8080"
      - "52000-52100:52000-52100/udp"
    environment:
      NEKO_SCREEN: 1920x1080@30
      NEKO_PASSWORD: neko
      NEKO_PASSWORD_ADMIN: admin
      NEKO_EPR: 52000-52100
      NEKO_ICELITE: 1
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
